name: Cloud Tasks Queue Creation

on:
  workflow_dispatch:
    inputs:
      tasks_location:
        description: "Cloud Tasks Location (e.g., asia-northeast1)"
        required: true
        default: "asia-northeast1"
        type: string
      cloud_run_url:
        description: "Cloud Run Service URL (e.g., https://api-service-abc123-an.a.run.app)"
        required: true
        type: string
      tasks_queue_name:
        description: "Cloud Tasks Queue Name"
        required: true
        default: "dish-que"
        type: string

jobs:
  create-queue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Create Cloud Tasks Queue
        run: |
          gcloud tasks queues create "${{ github.event.inputs.tasks_queue_name }}" \
            --location="${{ github.event.inputs.tasks_location }}" \
            --project="${{ secrets.GCP_PROJECT_ID }}" \
            --quiet
